# Generated by Django 6.1.1 on 2026-09-23 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clicker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_made', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_received_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=60)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_preset', models.CharField(blank=True, default='bot_1', max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('daily_points', models.IntegerField(default=0)),
                ('clicks_given', models.IntegerField(default=0)),
                ('clicks_received', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=1)),
                ('clicks_given', models.IntegerField(default=0)),
                ('clicks_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'rank'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
