# Generated by Django 6.1.1 on 2026-09-23 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_active_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
